#!/usr/bin/perl -n

BEGIN {open TITLE_FH, '>', 'article-title-list'}

sub hash {
  local $_;
  my $h = 0;
  $h *= 5, $h ^= $_, $h &= 0xffffff for unpack 'U*', $_[0];
  printf STDERR "%s -> %04x\n", $_[0], $h & 0xffff;
  sprintf "%04x", $h & 0xffff;
}


close $fh, open($fh, '>>', 'articles/' . hash(lc $1)),
(print TITLE_FH $1, "\n"), print $fh $_
if s/^\s*\<title\>([^<]+)(<.*)$/<article>\n<title>\1\2/;

print $fh $_ if /^\s*\<timestamp\>/;

$text &&= !s/(\<\/text\>.*)$/\1\n<\/article>/g, print $fh $_
if $text ||= s/^(.*\<text[^>]*\>)/\1\n/;
