#!/usr/bin/perl
# Usage: retrieve <article title>

my $article_path = "$ENV{HOME}/transition/wikipedia/articles";

sub hash {
  local $_;
  my $h = 0;
  $h *= 5, $h ^= $_, $h &= 0xffffff for unpack 'U*', $_[0];
  sprintf "%04x", $h & 0xffff;
}

my $title = lc join ' ', @ARGV;
my $hash  = hash($title);
print STDERR "using $article_path/$hash\n";

open my($segment), "bzcat $article_path/$hash.bz2 |";

my $correct_article = 0;
my $text_part       = 0;

while (<$segment>) {
  $correct_article = $title eq lc $1 or print STDERR "."
  if /^\s*<title>([^>]+)<\/title>/;

  print, $text_part &&= !s/<\/text>.*$//
  if $correct_article and $text_part ||= s/^\s*<text[^>]*>//;
}

print STDERR "\n";
close $segment;
