#!/usr/bin/perl
# Usage: retrieve <article title>

sub hash {
  local $_;
  my $h = 0;
  $h *= 5, $h ^= $_, $h &= 0xffffff for unpack 'U*', $_[0];
  sprintf "%04x", $h & 0xffff;
}

my $title = lc join ' ', @ARGV;
open my($segment), '<', 'articles/' . hash($title);

my $correct_article = 0;
my $text_part       = 0;

while (<$segment>) {
  $correct_article = $title eq lc $1 if /^\s*<title>([^>]+)<\/title>/;

  print if $correct_article and $text_part ||= s/^\s*<text[^>]*>//;
  print, last if $correct_article and s/<\/text>\s*$//;
}

close $segment;
